#![allow(clippy::approx_constant)]

mod bbox;
mod build_context;
mod edge_type_store;
mod error;
pub mod line_segment;
mod r#match;
pub mod math;
mod offset;
mod operation;
mod origin_index;
mod origin_type;
mod path;
mod pattern;
mod pattern_radial;
mod phase;
mod point;
mod polygon;
mod polygons;
mod seed;
mod separator;
mod shape;
mod shape_type_store;
mod sibling_iterator;
mod tiling;
mod transform;
mod transform_continuous;
mod transform_eccentric;
mod transform_value;
mod transforms;
mod validator;
mod vertex_type_store;

pub use self::bbox::BBox;
pub use self::build_context::{BuildContext, ValidTiling};
pub use self::error::{ApplicationError, TilingError};
pub use self::line_segment::LineSegment;
pub use self::offset::Offset;
pub use self::operation::Operation;
pub use self::origin_index::OriginIndex;
pub use self::origin_type::OriginType;
pub use self::path::Path;
pub use self::pattern::{Pattern, Patterns};
pub use self::phase::Phase;
pub use self::point::Point;
pub use self::polygon::Polygon;
pub use self::polygons::Polygons;
pub use self::seed::Seed;
pub use self::separator::Separator;
pub use self::shape::Shape;
pub use self::tiling::Tiling;
pub use self::transform::Transform;
pub use self::transform_continuous::TransformContinuous;
pub use self::transform_eccentric::TransformEccentric;
pub use self::transform_value::TransformValue;
pub use self::transforms::Transforms;
pub use self::validator::{ValidationError, ValidationFlag, Validator};
