language: node_js
cache: yarn
branches:
  only:
  - master
script:
- yarn lint
before_deploy:
- yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: QCtEd4Qw1+qGex4VdGO72VlcCIO9er1rhbnA9yI6HNqP30JdbOWnODZifs7igLwh9z9eZQDPqX1K3cBfUbsJi6BXxUNjELVB6sXUvGwiXuA7L8A2QUR+rXH9C0+WlC/v1s3mswl3YfI+b/XbVLmebea3ryH1hcp9WNykb8ZIyCyrLEn3jxqbNbM5YaqUONnwKVDE1ZG+WIZXAfZrNV30ROcJgLSmATjoC4LyGULkF2H+cBYcFp8PNueCRty2GcwKU5f8PqZBigSVHKcYlsSGVoWUCXaKc1odETUte6qTVwjpur9iq/qwiJPkeMDMIRRyZFoBp3wKPKEPnw39dE0AAIbYBIqHV7O8qAy67hkNA0PH4ATpOJPPgNc1RhMNTiOVsBYk71qXSITVNJhyJyooA7lMZBJbe7vW5l3VteyL7zkse8IirIW1EIXhreom2UEJsM/nR1DWZSCN3S/x08TLg8w+cy3D75UVKWifDAG4jX0eXNQiPAbSR/hQgkn6/WUfKhFiE+GhG584/1bJ+/Y/46Gg3nzMwnONjnt8NMEkakvofb/agCT6OaYprrpKyM023QwoBGHlJiReNNGSozy4bP8YFSSA9Cdd6d/yKEBhBBFylTfdUsqP54J2ScuPTnWGVfhjvo00NAyhpZT4dakBLbZCHolqmEkBZzy5chpvVRc=

