/*
 Generated by typeshare 1.6.0
*/

export enum ScaleMode {
	Fixed = "Fixed",
	WithinBounds = "WithinBounds",
}

export interface Style {
	chevronSize?: number;
	fill?: string;
	fontFamily?: string;
	fontSize?: number;
	fontWeight?: string;
	lineDash?: number[];
	lineThickness?: number;
	opacity?: number;
	pointRadius?: number;
	strokeColor?: string;
	strokeWidth?: number;
	textAlignHorizontal?: string;
	textAlignVertical?: string;
}

export interface Styles {
	arc?: Style;
	debug?: Style;
	text?: Style;
}

export interface Options {
	autoRotate?: boolean;
	padding?: number;
	scaleMode?: ScaleMode;
	scaleSize?: number;
	showDebug?: boolean;
	styles: Styles;
}

