/*
 Generated by typeshare 1.9.2
*/

export interface Config {
	cell_size: number;
	genotype_size: number;
	phenotype_size: number;
	epistasis_gain: number;
	epistasis_edges_min: number;
	epistasis_edges_max: number;
	phenotype_gain: number;
	phenotype_edges_min: number;
	phenotype_edges_max: number;
	local_environment_gain: number;
	local_environment_effect_radius: number;
	local_environment_edges_min: number;
	local_environment_edges_max: number;
	regional_environment_gain: number;
	regional_environment_count: number;
	regional_environment_edges_min: number;
	regional_environment_edges_max: number;
	global_environment_gain: number;
	global_environment_edges_min: number;
	global_environment_edges_max: number;
	reproduction_search_radius: number;
}

export interface RunStats {
	passIndex: number;
	passesPerSecond: number;
}

export type Message = 
	| { name: "wasmReady", data?: undefined }
	| { name: "canvasTransferred", data?: undefined }
	| { name: "simulationInit", data?: undefined }
	| { name: "simulationLoopStarted", data?: undefined }
	| { name: "simulationLoopStopped", data?: undefined }
	| { name: "simulationPaused", data?: undefined }
	| { name: "simulationResumed", data?: undefined }
	| { name: "simulationReset", data?: undefined }
	| { name: "simulationRunStats", data: RunStats }
	| { name: "postUpdateIntervalSet", data: number }
	| { name: "dataConfigSet", data: Config }
	| { name: "dataMemoryUsageEstimated", data: string }
	| { name: "error", data: string }
	| { name: "log", data: string };

