/*
 Generated by typeshare 1.9.2
*/

export interface DataBufferReadContent {
	label: string;
	cellIndex: number;
	data: number[];
}

export interface Config {
	cellSize: number;
	genotypeSize: number;
	phenotypeSize: number;
	epistasisEnabled: boolean;
	epistasisGain: number;
	epistasisEdgesMin: number;
	epistasisEdgesMax: number;
	phenotypeGain: number;
	phenotypeEdgesMin: number;
	phenotypeEdgesMax: number;
	regionalEnvEnabled: boolean;
	regionalEnvCount: number;
	regionalEnvOverlap: number;
	regionalEnvEpiGain: number;
	regionalEnvEpiEdgesMin: number;
	regionalEnvEpiEdgesMax: number;
	regionalEnvFitGain: number;
	regionalEnvFitEdgesMin: number;
	regionalEnvFitEdgesMax: number;
	globalEnvEnabled: boolean;
	globalEnvEpiGain: number;
	globalEnvEpiEdgesMin: number;
	globalEnvEpiEdgesMax: number;
	globalEnvFitGain: number;
	globalEnvFitEdgesMin: number;
	globalEnvFitEdgesMax: number;
	partnershipOpportunitiesMax: number;
	partnershipFitnessAmplification: number;
	partnershipFitnessEdgesMin: number;
	partnershipFitnessEdgesMax: number;
	partnershipMonogamyAmplification: number;
	partnershipMonogamyEdgesMin: number;
	partnershipMonogamyEdgesMax: number;
}

export interface RunStats {
	passIndex: number;
	passesPerSecond: number;
}

export type Message = 
	| { name: "wasmReady", data?: undefined }
	| { name: "canvasTransferred", data?: undefined }
	| { name: "simulationInit", data?: undefined }
	| { name: "simulationLoopStarted", data?: undefined }
	| { name: "simulationLoopStopped", data?: undefined }
	| { name: "simulationPaused", data?: undefined }
	| { name: "simulationResumed", data?: undefined }
	| { name: "simulationReset", data?: undefined }
	| { name: "simulationRunStats", data: RunStats }
	| { name: "postUpdateIntervalSet", data: number }
	| { name: "dataConfigSet", data: Config }
	| { name: "dataMemoryUsageEstimated", data: string }
	| { name: "dataBufferRead", data: DataBufferReadContent }
	| { name: "error", data: string }
	| { name: "log", data: string };

