/*
 Generated by typeshare 1.9.2
*/

export type Message = 
	| { name: "wasmReady", data?: undefined }
	| { name: "canvasTransferred", data?: undefined }
	| { name: "dimensionsSet", data?: undefined }
	| { name: "simulationInit", data?: undefined }
	| { name: "simulationLoopStarted", data?: undefined }
	| { name: "simulationLoopStopped", data?: undefined }
	| { name: "postUpdateIntervalSet", data: number }
	| { name: "error", data: string }
	| { name: "log", data: string };

