/*
 Generated by typeshare 1.5.0
*/

export interface Point {
	x: number;
	y: number;
}

export interface BBox {
	min: Point;
	max: Point;
}

export interface LineSegment {
	p1: Point;
	p2: Point;
}

export interface Polygon {
	bbox: BBox;
	centroid: Point;
	line_segments: LineSegment[];
	points: Point[];
}

