name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          cache-workspaces: true
          components: clippy, rustfmt
          toolchain: 1.85.0
      - name: 'Install dependencies: Node'
        run: yarn
      - name: 'Install dependencies: Rust'
        run: cargo fetch
      - name: 'Install dependencies: wasm-pack'
        run: cargo install wasm-pack
      - name: 'Install dependencies: typeshare'
        run: cargo install typeshare-cli
      - name: 'Install dependencies: wasm32-unknown-unknown'
        run: rustup target add wasm32-unknown-unknown
      - name: 'Build'
        run: yarn build
      - name: 'Lint'
        run: yarn lint
      - name: 'Test'
        run: yarn test:ci
      - name: Prepare Google Application Credentials for Firebase deploy
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" | base64 --decode > "$RUNNER_TEMP/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp-key.json" >> "$GITHUB_ENV"
      - name: 'Deploy'
        run: yarn firebase deploy
